# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c716252e123106cee9ea444bfda84ee5cdbae9f8ea0c5ea22fa2102b3ce334ac9e6f7ce7874bc4ef44b0b51c493515e210d725ff2e685141f43f93374e9a6e1

test:
  secret_key_base: dc854890cbca12e8baa8388d70af55def51d1a6e16e8e0c57347dae24be7185059ab6cdf950d7bdc3a23d312c333684881bb7bd6fd7301a1ecc5e29985c6adfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
